spring:
  application:
    name: paasta-delivery-pipeline-inspection-api
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb

---
spring:
  profiles:
    active: local

server:
  port: {SERVER-PORT}

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

inspection:
  server:
    url: INSPECTION-SERVER-URL
    admin:
      username: INSPECTION-SERVER-ADMIN-USER-NAME
      password: INSPECTION-SERVER-ADMIN-PASSWORD

commonApi:
  url: COMMOM-API-URL
  authorization:
    id: COMMOM-API-AUTHORIZATION-ID
    password: COMMOM-API-AUTHORIZATION-PASSWORD

---
spring:
  profiles: dev

logging:
  level:
    ROOT: DEBUG
  path: classpath:logback-spring.xml
  file: logs/application.log

server:
  port: {SERVER-PORT}

inspection:
  server:
    url: INSPECTION-SERVER-URL
    admin:
      username: INSPECTION-SERVER-ADMIN-USER-NAME
      password: INSPECTION-SERVER-ADMIN-PASSWORD

commonApi:
  url: COMMOM-API-URL
  authorization:
    id: COMMOM-API-AUTHORIZATION-ID
    password: COMMOM-API-AUTHORIZATION-PASSWORD